### ISSUE TITLE
Can someone help me get a basic local Vite server to serve api's?

### ISSUE THREAD

**Issue by kevbook** [magne4000/vite-plugin-vercel#19]
Can someone help me get a basic Vite server to serve api's running locally?

```ts
// vite.config.js
import { defineConfig } from 'vite';
import vercel from 'vite-plugin-vercel';

export default defineConfig({
  plugins: [
    vercel({
      smart: false,
    }),
  ],
});

// api/endpoint.ts
export default function handler() {
  return new Response(JSON.stringify({ a: true }), {
    status: 200,
    headers: {
      'content-type': 'application/json',
    },
  });
}
```

Curl returns the source code of the file

```sh
VITE v4.4.9  ready in 301 ms
➜  Local:   http://localhost:5173/

$ curl http://localhost:5173/api/endpoint

// Returns 
export default function handler() {
  return new Response(JSON.stringify({ a: true }), {
    status: 200,
    headers: {
      "content-type": "application/json"
    }
  });
}
```

**Comment by magne4000** [comment]
You have multiple solutions here:
- Use `vite-plugin-ssr`, it will handle filesystem routing for you
- Use `vercel dev` instead of `pnpm dev` to run your project. You should be aware that using `api` folder can result in a [conflict with `@vercel/build`](https://github.com/magne4000/vite-plugin-vercel/blob/a6c69d4cba9018660bd9827035d3db0a53be2240/packages/vercel/src/build.ts#L31-L33).
- Create a [server file like in the demo folder](https://github.com/magne4000/vite-plugin-vercel/blob/main/examples/demo/server/index.ts), in which you add your `/api` rules. Here is an example:

```ts
import express from 'express';
import endpoint from '../api/endpoint';

const app = express();
...
app.all('/api/endpoint', endpoint);
...
app.listen(3000);
```

I also updated the simple example, see https://github.com/magne4000/vite-plugin-vercel/commit/ff93906156bd95634b1759d438e9586b60ad12ca

**Comment by magne4000** [comment]
I also [created an issue](https://github.com/magne4000/vite-plugin-vercel/issues/20) to investigate if this could be solved by this plugin directly (without conflicting with mentionned solutions).

**Comment by kevbook** [comment]
Thank you!
