### ISSUE TITLE
How to use this plugin on my Vite SSR project?

### ISSUE THREAD

**Issue by slivermoe** [magne4000/vite-plugin-vercel#41]
I installed this plugin into my project. After I deployed to Vercel, it showed index normally but returned 404 back to me when I tried to visit other pages.
I don't sure if something is wrong. My config was actting in accordance with examples/simple.

**Comment by magne4000** [comment]
What is your complete vite config?
Also what files are generated under `.vercel` folder upon `build`?

**Comment by gxres042** [comment]
> What is your complete vite config? Also what files are generated under `.vercel` folder upon `build`?

``` typescript
// vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vercel from 'vite-plugin-vercel';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), vercel()]
})
```
``` json
// .vercel/output/config.json
{
  "version": 3,
  "routes": [
    {
      "src": "^/(?:(.+)/)?index(?:\\.html)?/?$",
      "headers": {
        "Location": "/$1"
      },
      "status": 308
    },
    {
      "src": "^/(.*)\\.html/?$",
      "headers": {
        "Location": "/$1"
      },
      "status": 308
    }
  ],
  "overrides": {}
}
```

**Comment by magne4000** [comment]
I do not have enough information to be able to help. Could you please share your code or a small reproduction repo so that I can help?

**Comment by gxres042** [comment]
> I do not have enough information to be able to help. Could you please share your code or a small reproduction repo so that I can help?

`pnpm create create-vite-extra`
Select ssr-vue
Install `vite-plugin-vercel` as devDependencies
Import vite-plugin-vercel into vite.config.ts
Simply configure vue-router
Deploy to Vercel, shows 404

I followed these step to reproduce.

**Comment by magne4000** [comment]
Let me check that

**Comment by magne4000** [comment]
@gxres042 I think for this to work it would need a custom integration between this plugin and `vue-router`, like there is one for [Vike](https://github.com/magne4000/vite-plugin-vercel?tab=readme-ov-file#usage-with-vike).
The reason is that Vite itself doesn't have a generic concept of routes, so each framework needs a custom integration.

If you do not need avanced features like ISR, I would suggest sticking with [Vercel's default support for vue](https://vercel.com/guides/deploying-vuejs-to-vercel).

Otherwise, a custom `@vite-plugin-vercel/vue-router` would need to be created (PR welcome).
