### ISSUE TITLE
how to use with @tanstack/react-router

### ISSUE THREAD

**Issue by dohomi** [magne4000/vite-plugin-vercel#54]
I tried to enable this plugin wichin my tanstack router project. But any /api/* route still responses with 404 error from tanstack router. I used `vite-plugin-vercel-api` plugin where it seems to work. Any idea how this could be archived?

**Comment by magne4000** [comment]
This project main goal is to implement features of the [Build Output API (v3)](https://vercel.com/docs/build-output-api/v3).

`vite-plugin-vercel` currently [does not currently support `/api` endpoint in developement](https://github.com/magne4000/vite-plugin-vercel/issues/20), only for build process.
I think that it should work in concert with `vite-plugin-vercel-api` though.

Also, I'm not familiar with `@tanstack/react-router`, and it could require a deeper integration even for the build process. `vite-plugin-vercel` gives you somes helpers and guidelines in order to build your own implementation on top of it (in this case on top of `@tanstack/react-router`). [Vike integration](https://github.com/magne4000/vite-plugin-vercel/tree/main/packages/vike-integration) can be taken as a complete example of how to do that.

**Comment by dohomi** [comment]
OK cool, thanks for your reply. Will close this issue as I found a way around to simply use transpiled /api folder.
